// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt6kWhOul4qqBwaRjEdfBhvGYU3BubMlk',
    appId: '1:81845148430:web:085bd1ab16ceeb030b955f',
    messagingSenderId: '81845148430',
    projectId: 'fall-9250a',
    authDomain: 'fall-9250a.firebaseapp.com',
    storageBucket: 'fall-9250a.firebasestorage.app',
    measurementId: 'G-0T67DCRTZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCT7ADCd25C8sWmpurQ7xXmtgj7jKf-Fs',
    appId: '1:81845148430:android:5265b393577037c90b955f',
    messagingSenderId: '81845148430',
    projectId: 'fall-9250a',
    storageBucket: 'fall-9250a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQO_waRcjBO2t2nIZxDJxDeslFSFJ20q0',
    appId: '1:81845148430:ios:27b77257d6abf81c0b955f',
    messagingSenderId: '81845148430',
    projectId: 'fall-9250a',
    storageBucket: 'fall-9250a.firebasestorage.app',
    iosBundleId: 'com.ldr.ldrApp',
  );
}
