name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0' # Uses a stable, recent version of Flutter
          channel: 'stable'

      - name: Create .env file from Secrets
        working-directory: ./ldr_app
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" > .env
          echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env

      - name: Install Dependencies
        working-directory: ./ldr_app
        run: flutter pub get

      - name: Build APK
        working-directory: ./ldr_app
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fall-ldr-app-apk
          path: ldr_app/build/app/outputs/flutter-apk/app-release.apk
