name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create .env file from Secrets
        working-directory: ./ldr_app
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" > .env
          echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env
          echo "LIVEKIT_URL=${{ secrets.LIVEKIT_URL }}" >> .env
          echo "LIVEKIT_API_KEY=${{ secrets.LIVEKIT_API_KEY }}" >> .env
          echo "LIVEKIT_API_SECRET=${{ secrets.LIVEKIT_API_SECRET }}" >> .env

      - name: Install Dependencies
        working-directory: ./ldr_app
        run: flutter pub get

      - name: Build APK
        working-directory: ./ldr_app
        run: flutter build apk --release

      - name: Rename APK
        working-directory: ./ldr_app
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/fall.apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fall-ldr-app-apk
          path: ldr_app/build/app/outputs/flutter-apk/fall.apk

      - name: Create Release (Direct APK Download)
        uses: ncipollo/release-action@v1
        with:
          artifacts: "ldr_app/build/app/outputs/flutter-apk/fall.apk"
          tag: "latest"
          name: "Latest Android Build"
          body: "Download the raw `fall.apk` file below to install the app directly on your phone!"
          allowUpdates: true
          replacesArtifacts: true
